const MIME_TYPE = {
    TXT: 'text/plain',
    CSV: 'text/csv'
}

const DESTINATION_PATH = 'D:\\D5-TOOLS-TEST\\'

const MAX_LINE_IN_SHEET = 18

const SPECIAL_CHARACTERS = {
    CIRCLE_CHECK: '〇'
}

export { MIME_TYPE, DESTINATION_PATH, MAX_LINE_IN_SHEET, SPECIAL_CHARACTERS }