export const HANDLE_COPY = 'HANDLE_COPY';
export const DELETE_TEXTS = 'DELETE_TEXTS';
export const SET_CONTENT = 'SET_CONTENT';
export const SET_NUMBER = 'SET_NUMBER';
export const SET_SELECTED_ITEM_LEFT_CONTENT_TAB_COMPONENT = 'SET_SELECTED_ITEM_LEFT_CONTENT_TAB_COMPONENT';